name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Lint with Flake8
        run: |
          pipx run flake8
          
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9" 

      - name: Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]

      - name: Run Tests with Pytest
        run: |
          pytest --verbose 
